[versions]
kotlin = "2.4.10"
catengine = "1.0.0"
gson = "2.13.2"
sqlite = "3.51.3.0"

paper-api = "26.1.2.build.+"
minecraft = "26.1.2"

shadow = "9.6.1"
run-task = "3.1.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
catengine-common = { module = "net.catmine:catengine-common", version.ref = "catengine" }
catengine-database = { module = "net.catmine:catengine-database", version.ref = "catengine" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
